version: '3.9'

name: grupo-amazonas-case2

services:
  db:
    image: postgres:latest
    container_name: grupo-amazonas-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "--username", "postgres" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  nestjs-app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
    command: [ "/app/wait-for-it.sh", "npm", "run", "start:prod" ]
    networks:
      - app-network

volumes:
  pg_data:
    driver: local

networks:
  app-network:
    driver: bridge
